import { RiskConfigError } from './errors';

export const GROUP_A_REASON_CODES = Object.freeze([
  'INVALID_ENTRY_PRICE', 'INVALID_STOP_PRICE', 'INVALID_STOP_DISTANCE', 'RISK_BUDGET_NON_POSITIVE',
  'MIN_QUANTITY_NOT_MET', 'MIN_NOTIONAL_NOT_MET', 'INSUFFICIENT_MARGIN', 'NO_VALID_LEVERAGE_TIER',
  'INSTRUMENT_NOT_TRADEABLE_FOR_NEW_EXPOSURE', 'GLOBAL_EXPOSURE_LIMIT', 'PAIR_EXPOSURE_LIMIT',
  'STRATEGY_EXPOSURE_LIMIT', 'MAX_CONCURRENT_POSITIONS', 'DAILY_LOSS_LIMIT',
  'DAILY_LOSS_PERCENT_LIMIT', 'DRAWDOWN_LIMIT', 'CONSECUTIVE_LOSS_COOLDOWN_ACTIVE',
  'NO_CHANGE_TARGET_ALREADY_HELD', 'REVERSAL_REQUIRES_SEQUENTIAL_EVALUATION',
] as const);

export const GROUP_B_REASON_CODES = Object.freeze([
  'ACCOUNT_STATE_UNAVAILABLE', 'ACCOUNT_STATE_STALE', 'ACCOUNT_IDENTITY_MISMATCH', 'PAIR_STATE_UNAVAILABLE',
  'EXPOSURE_STATE_UNAVAILABLE', 'EXPOSURE_STATE_STALE', 'PENDING_EXPOSURE_UNKNOWN',
  'POSITION_OWNERSHIP_UNRECONCILED', 'POSITION_OWNERSHIP_MISMATCH', 'POSITION_IDENTITY_MISMATCH',
  'EVIDENCE_TEMPORAL_CAUSALITY_VIOLATION', 'SOURCE_ID_MISMATCH', 'VALUATION_METHOD_MISMATCH',
  'VALUATION_NUMERIC_CONTEXT_EXCEEDED', 'LEVERAGE_TIERS_UNAVAILABLE', 'LEVERAGE_TIERS_STALE',
  'LEVERAGE_TIER_SEMANTICS_UNVERIFIED', 'SETTLEMENT_RATE_UNAVAILABLE', 'SETTLEMENT_RATE_STALE',
  'DECISION_IDENTITY_MISMATCH',
] as const);

export type RiskRejectionCode = typeof GROUP_A_REASON_CODES[number] | typeof GROUP_B_REASON_CODES[number];

export const REJECTION_PRECEDENCE_V1: readonly RiskRejectionCode[] = Object.freeze([
  'DECISION_IDENTITY_MISMATCH', 'ACCOUNT_IDENTITY_MISMATCH', 'POSITION_IDENTITY_MISMATCH',
  'SOURCE_ID_MISMATCH', 'VALUATION_METHOD_MISMATCH', 'VALUATION_NUMERIC_CONTEXT_EXCEEDED', 'PAIR_STATE_UNAVAILABLE',
  'EVIDENCE_TEMPORAL_CAUSALITY_VIOLATION', 'ACCOUNT_STATE_UNAVAILABLE', 'ACCOUNT_STATE_STALE',
  'EXPOSURE_STATE_UNAVAILABLE', 'EXPOSURE_STATE_STALE', 'LEVERAGE_TIERS_UNAVAILABLE', 'LEVERAGE_TIERS_STALE',
  'LEVERAGE_TIER_SEMANTICS_UNVERIFIED', 'SETTLEMENT_RATE_UNAVAILABLE', 'SETTLEMENT_RATE_STALE',
  'NO_CHANGE_TARGET_ALREADY_HELD', 'REVERSAL_REQUIRES_SEQUENTIAL_EVALUATION',
  'INSTRUMENT_NOT_TRADEABLE_FOR_NEW_EXPOSURE', 'INVALID_ENTRY_PRICE', 'INVALID_STOP_PRICE', 'INVALID_STOP_DISTANCE',
  'PENDING_EXPOSURE_UNKNOWN', 'POSITION_OWNERSHIP_UNRECONCILED', 'POSITION_OWNERSHIP_MISMATCH',
  'RISK_BUDGET_NON_POSITIVE', 'NO_VALID_LEVERAGE_TIER', 'INSUFFICIENT_MARGIN', 'MIN_QUANTITY_NOT_MET',
  'MIN_NOTIONAL_NOT_MET', 'GLOBAL_EXPOSURE_LIMIT', 'PAIR_EXPOSURE_LIMIT', 'STRATEGY_EXPOSURE_LIMIT',
  'MAX_CONCURRENT_POSITIONS', 'DAILY_LOSS_LIMIT', 'DAILY_LOSS_PERCENT_LIMIT', 'DRAWDOWN_LIMIT',
  'CONSECUTIVE_LOSS_COOLDOWN_ACTIVE',
] as const);

const CANONICAL_REASON_CODES: ReadonlySet<string> = new Set([
  ...GROUP_A_REASON_CODES,
  ...GROUP_B_REASON_CODES,
]);

export function assertRejectionPrecedenceIntegrity(precedence: readonly string[] = REJECTION_PRECEDENCE_V1): void {
  const known = [...GROUP_A_REASON_CODES, ...GROUP_B_REASON_CODES];
  if (precedence.length !== known.length || new Set(precedence).size !== precedence.length ||
      known.some((code) => !precedence.includes(code)) || precedence.some((code) => !known.includes(code as RiskRejectionCode))) {
    throw new RiskConfigError('RISK_CONFIG_INVALID', 'Rejection precedence must contain every Group A/B code exactly once');
  }
}

export function orderReasonCodes(codes: Iterable<RiskRejectionCode>): readonly RiskRejectionCode[] {
  const set = new Set(codes);
  for (const code of set) {
    if (!CANONICAL_REASON_CODES.has(code) || !REJECTION_PRECEDENCE_V1.includes(code)) {
      throw new RiskConfigError('RISK_CONFIG_INVALID', `Rejection reason ${code} is absent from canonical precedence`);
    }
  }
  return Object.freeze(REJECTION_PRECEDENCE_V1.filter((code) => set.has(code)));
}
